# --- !Ups

create table "people"
(
    "id"   bigint generated by default as identity (start with 1) not null primary key,
    "name" varchar not null,
    "age"  int     not null
);

CREATE TABLE "category"
(
    "category_id"   INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "category_name" TEXT    NOT NULL
);

CREATE TABLE "order"
(
    "order_id"      INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "user_id"       INTEGER NOT NULL,
    "order_date"    TEXT    NOT NULL,
    "order_address" TEXT    NOT NULL
);

CREATE TABLE "order_detail"
(
    "order_product_id"       INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "order_id"               INTEGER NOT NULL,
    "product_id"             INTEGER NOT NULL,
    "order_product_quantity" TEXT    NOT NULL,
    FOREIGN KEY ("order_id") REFERENCES "order"
);


CREATE TABLE "product"
(
    "product_id"          INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "product_name"        TEXT    NOT NULL,
    "product_description" TEXT    NOT NULL,
    "product_price"       INTEGER NOT NULL,
    "product_unavailable" TEXT,
    "category_id"         INTEGER NOT NULL,
    FOREIGN KEY ("category_id") REFERENCES "category" ("id")
);

CREATE TABLE "user"
(
    "user_id"       INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "user_name"     TEXT    NOT NULL,
    "user_password" TEXT    NOT NULL,
    "user_email"    TEXT    NOT NULL,
    "user_country"  TEXT    NOT NULL,
    "user_street"   TEXT    NOT NULL,
    "user_city"     TEXT    NOT NULL,
    "user_address"  TEXT    NOT NULL,
    "user_postal"   TEXT    NOT NULL
);
# --- !Downs

drop table "people" if exists;
drop table "category" if exists;
drop table "order" if exists;
drop table "order_detail" if exists;
drop table "product" if exists;
drop table "user" if exists;
